# Generated by Django 3.1 on 2020-08-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game_rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50, verbose_name='name')),
                ('room_password', models.CharField(max_length=50, verbose_name='password')),
                ('room_settings_player_quantities', models.IntegerField(verbose_name='player_quantities')),
                ('room_settings_duration', models.IntegerField(verbose_name='duration')),
                ('room_settings_vote_duration', models.IntegerField(verbose_name='vote_duration')),
            ],
        ),
    ]
