# Generated by Django 3.1 on 2020-08-12 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joined_players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('joined_players_quantities', models.IntegerField(default=0, null=True)),
                ('player_1', models.CharField(max_length=100, null=True)),
                ('player_2', models.CharField(max_length=100, null=True)),
                ('player_3', models.CharField(max_length=100, null=True)),
                ('player_4', models.CharField(max_length=100, null=True)),
                ('player_5', models.CharField(max_length=100, null=True)),
                ('player_6', models.CharField(max_length=100, null=True)),
                ('player_7', models.CharField(max_length=100, null=True)),
                ('player_8', models.CharField(max_length=100, null=True)),
                ('player_9', models.CharField(max_length=100, null=True)),
                ('player_10', models.CharField(max_length=100, null=True)),
                ('player_11', models.CharField(max_length=100, null=True)),
                ('player_12', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='game_rooms',
            name='room_joined_players',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rooms.joined_players'),
        ),
    ]
