# Generated by Django 3.1 on 2020-08-17 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200812_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_rooms',
            name='room_joined_players',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.joined_players'),
        ),
    ]
