# Generated by Django 3.1 on 2020-08-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200813_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_user',
            name='image_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='game_user',
            name='image',
            field=models.FileField(null=True, upload_to='templates/users'),
        ),
    ]
